name: bancoestadoqr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-65.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.0.0
  cached_network_image: ^3.2.3
  get: ^4.6.5
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    
